config/routes.rb
Rails.application.routes.draw do
  get 'quiz/index'
  get 'quiz/new'
  get 'pokemons/index'
  get 'pokemons/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
    
    if @pokemon == Quiz.where(name: 'params[:answer]').or(Quiz.where(number: params[:answer]))
    end
    
  end

  def new
    num = rand (1..52)
    @pokemon =  Quiz.find(num)
    # @pokemon = Pokemon.where(name: 'params[:search]').or(Pokemon.where(number: params[:search]))
    #↑ 送られてきたパラメータ(#{params[:search]}) を用いてDBより名前か番号で検索
    
    
    if @pokemon == nil
      redirect_to pokes_new_path, notice: "エラー！" 
      # また、リクエストが失敗した時の処理も追加します。
    end
    # ここまで追加

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonQuiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Pokemons#index</h1>
<p>Find me in app/views/pokemons/index.html.erb</p>

app/views/pokemons/new.html.erb
<h1>Pokemons#new</h1>
<p>Find me in app/views/pokemons/new.html.erb</p>

app/views/quiz/index.html.erb
<div>

  <div class="title">正解したポケモン</div>
  <% if @pokemon.present? %>
    <% @pokes.each do |poke| %>
      <div style="display: inline-block;">
        図鑑No. <%= poke.order %>
        名前: <%= poke.name %>
        <div>
          <%= image_tag(poke.image_url, size: "200") %>
        </div>
        <%= button_to "逃がす", poke_path(poke.id), method: :delete, class:"button is-rounded"%>
        

        </div>
    <% end %>
  <% end %>
  <%= link_to '次の問題へ', quiz_new_path %>
</div>

app/views/quiz/new.html.erb
<div class="body">  
  <h1 class="title"> このポケモンだーれだ！ </h1>
    <div class="column is-8">
      <div class="p-description">

      <% if @pokemon.present? %>

        <table>
        <tr><td id="td1">たかさ　：</td><td id="td2"><%= @pokemon.height %></td></tr>
        <tr><td id="td1">おもさ　：</td><td id="td2"><%= @pokemon.weight %></td></tr>
        <tr><td id="td1">タイプ　：</td><td id="td2"><%= @pokemon.types %></td></tr>
        <tr><td id="td1">図鑑説明：</td><td id="td2"><%= @pokemon.description %></td></tr>
        </table>



        <!--ヒントを取得-->
        <script>
          var h_1 = '<%= @pokemon.hint1 %>';
          var h_2 = '<%= @pokemon.hint2 %>';
          var h_3 = '<%= @pokemon.hint3 %>';
        </script>

        <!--ヒントボタン-->
        <!--スクリプトタブの中で変数に代入すれば使える　※シングルクォーテーション必須-->
        <button class ="btn--orange" id = "hint1" onclick="alert(h_1)">ヒント1</button>
        <button class ="btn--orange" id = "hint2" onclick="alert(h_2)">ヒント2</button>
        <button class ="btn--orange" id = "hint3" onclick="alert(h_3)">ヒント3</button>
        
        <br>

        <%= render "shared/search", { path: quiz_index_path } %>

        <script language="javascript" type="text/javascript">
          showMessage = () => {
            /*formに入力された情報の取得*/
            textbox = document.getElementById("input-message");
            inputValue = textbox.value;
            /*表示する内容設定*/
            output = "答え：" + inputValue;
            var str = '<%= @pokemon.name %>';
            var miss = "残念^^";


            /*ポップアップの入力指示*/
            const clickBtn = document.getElementById('click-btn');
            const popupWrapper = document.getElementById('popup-wrapper');
            const close = document.getElementById('close');
            

            if(inputValue === str){
              /*答えの名前と画像の表示*/
              document.getElementById("output-message").innerHTML = output;
              document.getElementById("image").innerHTML = image;
              /*ポップアップの表示*/
              popupWrapper.style.display = "block";
              /*次へボタン*/
              nextbutton.style.display = "block";

              /*xを押したらポップアップが消える*/
              popupWrapper.addEventListener('click', e => {
                if (e.target.id === popupWrapper.id || e.target.id === close.id) {
                  popupWrapper.style.display = 'none';
                }
              });
              
              /*正解なら入力フォームを消す。*/
              form1.style.display = 'none';

            }else{
              /*不正解の場合の表示*/
              document.getElementById("output-message").innerHTML = miss;
            }  
          }
        </script>

        <% end %>
      <!--
        <!--ポップアップ　cssにより初期は非表示-->
        <div id="popup-wrapper">
          <div id="popup-inside">
            <div id="close">x</div>
              <div id="message">
                <!-- <h2>正解！！</h2> -->
            </div>
          </div>
        </div> 
        

      </div>
    </div>
</div>

app/views/shared/_search.html.erb
<div style="margin-bottom: 50px;">
  <%= form_with url: path, method: :get, local: true do |form| %>
    <%= form.text_field :answer %>
    <%= form.submit '回答', name: nil %>
  <% end %>
</div>